plugins {
    id 'com.android.test'
    id 'androidx.baselineprofile'
}

android {
    namespace 'com.learnova.baselineprofile'
    compileSdk 36

    defaultConfig {
        minSdk 28
        targetSdk 35
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    testOptions {
        managedDevices {
            localDevices {
                pixel2api35 {
                    device = "Pixel 2"
                    apiLevel = 35
                    systemImageSource = "aosp"
                }
            }
        }
    }
}

dependencies {
    implementation 'androidx.test.ext:junit:1.2.1'
    implementation 'androidx.test.uiautomator:uiautomator:2.3.0'
    implementation 'androidx.benchmark:benchmark-macro-junit4:1.5.0'
}

baselineProfile {
    targetProjectPath = ':app'
    managedDevices = ['pixel2api35']
    useConnectedDevices = false
}
