plugins {
    id 'com.android.test'
}

android {
    namespace 'com.learnova.macrobenchmark'
    compileSdk 36

    defaultConfig {
        targetProjectPath = ':app'
        minSdk 28
        targetSdk 35
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    testBuildType = 'benchmark'

    testOptions {
        managedDevices {
            devices {
                pixel2api35(com.android.build.api.dsl.ManagedVirtualDevice) {
                    device = "Pixel 2"
                    apiLevel = 35
                    systemImageSource = "aosp"
                }
            }
        }
    }
}

dependencies {
    implementation 'androidx.test.ext:junit:1.2.1'
    implementation 'androidx.test.uiautomator:uiautomator:2.3.0'
    implementation 'androidx.benchmark:benchmark-macro-junit4:1.5.0'
}
