plugins {
    id 'com.android.test'
}

android {
    namespace 'com.learnova.macrobenchmark'
    compileSdk 36

    defaultConfig {
        targetProjectPath = ':app'
        minSdk 28
        targetSdk 35
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        testInstrumentationRunnerArguments = [
            'androidx.benchmark.suppressErrors': 'EMULATOR'
        ]
    }

    buildTypes {
        benchmark {
            signingConfig signingConfigs.debug
            debuggable false
            minifyEnabled false
            shrinkResources false
            matchingFallbacks = ['release']
            proguardFiles 'proguard-rules.pro'
        }
    }

    testOptions {
        managedDevices {
            localDevices {
                pixel2api35 {
                    device = 'Pixel 2'
                    apiLevel = 35
                    systemImageSource = 'google_apis'
                }
            }
        }
    }
}

androidComponents {
    beforeVariants(selector().all()) {
        enabled = buildType == 'benchmark'
    }
}

dependencies {
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.3.0'
    androidTestImplementation 'androidx.benchmark:benchmark-macro-junit4:1.5.0'
    androidTestImplementation 'androidx.tracing:tracing:1.2.0'
    androidTestImplementation 'androidx.profileinstaller:profileinstaller:1.4.1'
    androidTestImplementation 'androidx.startup:startup-runtime:1.2.0'
    compileOnly 'com.google.errorprone:error_prone_annotations:2.36.0'
}
